export const allColumns = [
  "Order Date",
  "Order ID",
  "Order Name",
  "Remaining Days",
  "Preview Edit Status",
  "Editor",
  "Payment Status",
  "Files",
  "Order Status",
  "Order Type",
  "User's Name",
  "User Email",
  "User Phone",
  "Delivery Date",
  "Price",
  "Download Link",
  "", // this field for icons
];

export const allRowsData = [
  {
    date: "2023-07-19",
    id: "TX3857",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "Approved",
    editorName: "Ayman",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file1",
    orderStatus: "Completed",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },

  {
    date: "2023-07-19",
    id: "TX1948",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "N/A",
    editorName: "editor name x",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file2",
    orderStatus: "Pending",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },
  {
    date: "2023-07-19",
    id: "TX4703",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "Rejected",
    editorName: "editor name y",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file3",
    orderStatus: "Pending",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },
  {
    date: "2023-07-19",
    id: "TX5612",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "N/A",
    editorName: "editor name z",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file4",
    orderStatus: "Cancelled",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },

  {
    date: "2023-07-19",
    id: "TX8243",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "Pending",
    editorName: "editor name xx1",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file5",
    orderStatus: "Preview Edit",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },
  {
    date: "2023-07-19",
    id: "TX6371",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "Pending",
    editorName: "editor name xx2",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file6",
    orderStatus: "Pending",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },
  {
    date: "2023-07-19",
    id: "TX2936",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "Pending",
    editorName: "editor name xx3",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file7",
    orderStatus: "Pending",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },

  {
    date: "2023-07-19",
    id: "TX4029",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "Pending",
    editorName: "editor name x yy1",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file8",
    orderStatus: "Pending",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },

  {
    date: "2023-07-19",
    id: "TX7154",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "Pending",
    editorName: "editor name yy2",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file9",
    orderStatus: "Pending",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },
  {
    date: "2023-07-19",
    id: "TX1248",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "Pending",
    editorName: "editor name yy3",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file10",
    orderStatus: "Pending",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },
];
