export const allColumnsData = [
  "Order Date",
  "Order ID",
  "Order Name",
  "Remaining Days",
  "Preview Edit Status",
  "Editor",
  "Payment Status",
  "Files",
  "Order Status",
  "Order Type",
  "User's Name",
  "User Email",
  "User Phone",
  "Delivery Date",
  "Price",
  "Download Link",
  "", // this field for icons
];

export const allRowsData = [
  {
    date: "2023-07-19",
    id: "TX3857",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "Approved",
    editorName: "Ayman",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file1",
    orderStatus: "Completed",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },

  {
    date: "2023-07-19",
    id: "TX1948",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "N/A",
    editorName: "Jane Smith",
    paymentStatus: "Pending",
    files: "https://drive.google.com/file/d/1/file2",
    orderStatus: "Pending",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },
  {
    date: "2023-07-19",
    id: "TX4703",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "Rejected",
    editorName: "Michael Brown",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file3",
    orderStatus: "Pending",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },
  {
    date: "2023-07-19",
    id: "TX5612",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "N/A",
    editorName: "Jane Smith",
    paymentStatus: "Due",
    files: "https://drive.google.com/file/d/1/file4",
    orderStatus: "Cancelled",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },

  {
    date: "2023-07-19",
    id: "TX8243",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "Pending",
    editorName: "Michael Brown",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file5",
    orderStatus: "Preview Edit",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },
  {
    date: "2023-07-19",
    id: "TX6371",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "Pending",
    editorName: "Assign Editor",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file6",
    orderStatus: "Pending",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },
  {
    date: "2023-07-19",
    id: "TX2936",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "Pending",
    editorName: "Assign Editor",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file7",
    orderStatus: "Pending",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },

  {
    date: "2023-07-19",
    id: "TX4029",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "Pending",
    editorName: "Assign Editor",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file8",
    orderStatus: "Pending",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },

  {
    date: "2023-07-19",
    id: "TX7154",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "Pending",
    editorName: "Assign Editor",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file9",
    orderStatus: "Pending",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },
  {
    date: "2023-07-19",
    id: "TX1248",
    orderName: "Wedding Photos",
    remaining: "04/07 days",
    previewstatus: "Pending",
    editorName: "Assign Editor",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file10",
    orderStatus: "Pending",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "Jul 20 2023",
    price: "$100",
    files2: "https://drive.google.com/file/d/1/file2",
    icon: "",
  },
];
