export const columns = [
  "Order Date",
  "Order ID",
  "Remaining Days",
  "Preview Edit Status",
  "Editor",
  "Payment Status",
  "Files",
  "Order Status",
  "", // this field for icons
];

export const allColumns = [
  "Order Date",
  "Order ID",
  "Order Name",
  "Preview Edit Status",
  "Remaining Days",
  "Order Type",
  "User's Name",
  "User Email",
  "User Phone",
  "Delivery Date",
  "Price",
  "Payment Status",
  "Editor",
  "Files",
  "Order Status",
  "Files2",
  "", // this field for icons
];

export const rowsData = [
  {
    date: "2023-07-19",
    id: "TX3857",
    remaining: "04/07 days",
    previewstatus: "Approved",
    editorName: "Ayman",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file1",
    orderStatus: "Completed",
    icon: "icon",
  },
  {
    date: "2023-07-19",
    id: "TX1948",
    remaining: "04/07 days",
    previewstatus: "N/A",
    editorName: "editor name x",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file2",
    orderStatus: "Pending",
    icon: "icon",
  },
  {
    date: "2023-07-19",
    id: "TX4703",
    remaining: "04/07 days",
    previewstatus: "Rejected",
    editorName: "editor name y",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file3",
    orderStatus: "Pending",
    icon: "icon",
  },
  {
    date: "2023-07-19",
    id: "TX5612",
    remaining: "04/07 days",
    previewstatus: "N/A",
    editorName: "editor name z",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file4",
    orderStatus: "Cancelled",
    icon: "icon",
  },
  {
    date: "2023-07-19",
    id: "TX8243",
    remaining: "04/07 days",
    previewstatus: "User Review Pending",
    editorName: "editor name xx1",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file5",
    orderStatus: "Preview Edit",
    icon: "icon",
  },
  {
    date: "2023-07-19",
    id: "TX6371",
    remaining: "04/07 days",
    previewstatus: "Pending",
    editorName: "editor name xx2",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file6",
    orderStatus: "Pending",
    icon: "icon",
  },
  {
    date: "2023-07-19",
    id: "TX2936",
    remaining: "04/07 days",
    previewstatus: "Pending",
    editorName: "editor name xx3",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file7",
    orderStatus: "Pending",
    icon: "icon",
  },
  {
    date: "2023-07-19",
    id: "TX4029",
    remaining: "04/07 days",
    previewstatus: "Pending",
    editorName: "editor name x yy1",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file8",
    orderStatus: "Pending",
    icon: "icon",
  },
  {
    date: "2023-07-19",
    id: "TX7154",
    remaining: "04/07 days",
    previewstatus: "Pending",
    editorName: "editor name yy2",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file9",
    orderStatus: "Pending",
    icon: "icon",
  },
  {
    date: "2023-07-19",
    id: "TX1248",
    remaining: "04/07 days",
    previewstatus: "Pending",
    editorName: "editor name yy3",
    paymentStatus: "Successful",
    files: "https://drive.google.com/file/d/1/file10",
    orderStatus: "Pending",
    icon: "icon",
  },
];

export const allRowsData = [
  {
    date: "2023-07-19",
    id: "TX1948",
    orderName: "Mr XP",
    orderType: "Express",
    usersName: "John Doe",
    userEmail: "john.doe@example.com",
    userPhone: "123-456-7890",
    deliveryDate: "2023-07-20",
    price: "$100",
    paymentStatus: "Successful",
    editorName: "Ayman",
    files: "https://drive.google.com/file/d/1/file1",
    orderStatus: "Completed",
    files2: "https://drive.google.com/file/d/1/file2",
    previewstatus: "Approved",
    remaining: "0/7 days",
    icon: "",
  },
  {
    date: "2023-07-20",
    id: "TX1949",
    orderName: "Ms YZ",
    orderType: "Standard",
    usersName: "Jane Smith",
    userEmail: "jane.smith@example.com",
    userPhone: "234-567-8901",
    deliveryDate: "2023-07-22",
    price: "$150",
    paymentStatus: "Pending",
    editorName: "Bilal",
    files: "https://drive.google.com/file/d/2/file1",
    orderStatus: "In Progress",
    files2: "https://drive.google.com/file/d/2/file2",
    previewstatus: "Pending",
    remaining: "2/7 days",
    icon: "",
  },
  {
    date: "2023-07-21",
    id: "TX1950",
    orderName: "Dr AB",
    orderType: "Express",
    usersName: "Alice Brown",
    userEmail: "alice.brown@example.com",
    userPhone: "345-678-9012",
    deliveryDate: "2023-07-21",
    price: "$200",
    paymentStatus: "Successful",
    editorName: "Carlos",
    files: "https://drive.google.com/file/d/3/file1",
    orderStatus: "Completed",
    files2: "https://drive.google.com/file/d/3/file2",
    previewstatus: "Approved",
    remaining: "0/7 days",
    icon: "",
  },
  {
    date: "2023-07-22",
    id: "TX1951",
    orderName: "Mr CD",
    orderType: "Standard",
    usersName: "Chris Davis",
    userEmail: "chris.davis@example.com",
    userPhone: "456-789-0123",
    deliveryDate: "2023-07-25",
    price: "$250",
    paymentStatus: "Failed",
    editorName: "Dana",
    files: "https://drive.google.com/file/d/4/file1",
    orderStatus: "Failed",
    files2: "https://drive.google.com/file/d/4/file2",
    previewstatus: "Rejected",
    remaining: "3/7 days",
    icon: "",
  },
  {
    date: "2023-07-23",
    id: "TX1952",
    orderName: "Ms EF",
    orderType: "Express",
    usersName: "Eva Green",
    userEmail: "eva.green@example.com",
    userPhone: "567-890-1234",
    deliveryDate: "2023-07-23",
    price: "$300",
    paymentStatus: "Successful",
    editorName: "Eli",
    files: "https://drive.google.com/file/d/5/file1",
    orderStatus: "Completed",
    files2: "https://drive.google.com/file/d/5/file2",
    previewstatus: "Approved",
    remaining: "0/7 days",
    icon: "",
  },
  {
    date: "2023-07-24",
    id: "TX1953",
    orderName: "Dr GH",
    orderType: "Standard",
    usersName: "George Hill",
    userEmail: "george.hill@example.com",
    userPhone: "678-901-2345",
    deliveryDate: "2023-07-27",
    price: "$350",
    paymentStatus: "Pending",
    editorName: "Fiona",
    files: "https://drive.google.com/file/d/6/file1",
    orderStatus: "In Progress",
    files2: "https://drive.google.com/file/d/6/file2",
    previewstatus: "Pending",
    remaining: "3/7 days",
    icon: "",
  },
  {
    date: "2023-07-25",
    id: "TX1954",
    orderName: "Mr IJ",
    orderType: "Express",
    usersName: "Isaac Jones",
    userEmail: "isaac.jones@example.com",
    userPhone: "789-012-3456",
    deliveryDate: "2023-07-25",
    price: "$400",
    paymentStatus: "Successful",
    editorName: "Grace",
    files: "https://drive.google.com/file/d/7/file1",
    orderStatus: "Completed",
    files2: "https://drive.google.com/file/d/7/file2",
    previewstatus: "Approved",
    remaining: "0/7 days",
    icon: "",
  },
  {
    date: "2023-07-26",
    id: "TX1955",
    orderName: "Ms KL",
    orderType: "Standard",
    usersName: "Kara Lee",
    userEmail: "kara.lee@example.com",
    userPhone: "890-123-4567",
    deliveryDate: "2023-07-29",
    price: "$450",
    paymentStatus: "Failed",
    editorName: "Hannah",
    files: "https://drive.google.com/file/d/8/file1",
    orderStatus: "Failed",
    files2: "https://drive.google.com/file/d/8/file2",
    previewstatus: "Rejected",
    remaining: "3/7 days",
    icon: "",
  },
  {
    date: "2023-07-27",
    id: "TX1956",
    orderName: "Dr MN",
    orderType: "Express",
    usersName: "Mona Nelson",
    userEmail: "mona.nelson@example.com",
    userPhone: "901-234-5678",
    deliveryDate: "2023-07-27",
    price: "$500",
    paymentStatus: "Successful",
    editorName: "Ivy",
    files: "https://drive.google.com/file/d/9/file1",
    orderStatus: "Completed",
    files2: "https://drive.google.com/file/d/9/file2",
    previewstatus: "Approved",
    remaining: "0/7 days",
    icon: "",
  },
  {
    date: "2023-07-28",
    id: "TX1957",
    orderName: "Mr OP",
    orderType: "Standard",
    usersName: "Oscar Perez",
    userEmail: "oscar.perez@example.com",
    userPhone: "012-345-6789",
    deliveryDate: "2023-07-31",
    price: "$550",
    paymentStatus: "Pending",
    editorName: "Jack",
    files: "https://drive.google.com/file/d/10/file1",
    orderStatus: "In Progress",
    files2: "https://drive.google.com/file/d/10/file2",
    previewstatus: "Pending",
    remaining: "3/7 days",
    icon: "",
  },
];
