export const allColumnsData = [
  // "Order Date",
  "Name",
  "Style Price",
  "Style Threshold",
  "Culling Price",
  "Culling Threshold",
  "Retouch Price",
  "Retouch Threshold",
  "Preview Price",
  "Preview Threshold",
  "",
];

export const allRowsData = [
  {
    name: "Wedding",
    stylePrice: "$0.30",
    styleThreshold: "500",
    cullingPrice: "$0.020",
    cullingThreshold: "1000",
    retouchPrice: "$1.00",
    retouchThreshold: "50",
    previewPrice: "$0.05",
    previewThreshold: "100",
    icon: "",
  },
  {
    name: "Headshot Portraits",
    stylePrice: "$0.40",
    styleThreshold: "20",
    cullingPrice: "$0.020",
    cullingThreshold: "50",
    retouchPrice: "$1.00",
    retouchThreshold: "20",
    previewPrice: "$0.05",
    previewThreshold: "100",
    icon: "",
  },
  {
    name: "Travel Photos",
    stylePrice: "$0.50",
    styleThreshold: "50",
    cullingPrice: "$0.020",
    cullingThreshold: "100",
    retouchPrice: "$1.00",
    retouchThreshold: "30",
    previewPrice: "$0.05",
    previewThreshold: "100",
    icon: "",
  },
];
